### ISSUE TITLE
No devices

### ISSUE THREAD

**Issue by archef2000** [lawrencebensaid/enet-api#2]
Hello i am trieing the cli version of package i auth successfully and get a session id but if i now try anything like `npm exec enet-api device ls` i get `Error: Unable to fetch devices at this time!` could you mayby help me to get a device list. ENet Server version is `2.3.0`.

**Comment by huglester** [comment]
please try to `npm exec enet-api auth USERNAME PASS 192.168.1.1`
first 

(similar as here: https://github.com/lawrencebensaid/enet-api/issues/1)

**Comment by archef2000** [comment]
![grafik](https://user-images.githubusercontent.com/69057532/210108430-0a91c983-a012-4559-b746-90bdff218ec3.png)
Already did that

**Comment by archef2000** [comment]
```bash
└─$ npm exec enet-api -d device ls
npm info using npm@8.19.2
npm info using node@v18.12.1
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 2ms
npm timing config:load:file:C:\Program Files\nodejs\node_modules\npm\npmrc Completed in 3ms
npm timing config:load:builtin Completed in 3ms
npm timing config:load:cli Completed in 2ms
npm timing config:load:env Completed in 1ms
npm timing config:load:project Completed in 3ms
npm timing config:load:file:C:\Users\user\.npmrc Completed in 0ms
npm timing config:load:user Completed in 0ms
npm timing config:load:file:C:\Users\user\AppData\Roaming\npm\etc\npmrc Completed in 0ms
npm timing config:load:global Completed in 1ms
npm timing config:load:validate Completed in 0ms
npm timing config:load:credentials Completed in 0ms
npm timing config:load:setEnvs Completed in 1ms
npm timing config:load Completed in 13ms
npm timing npm:load:configload Completed in 13ms
npm timing npm:load:mkdirpcache Completed in 1ms
npm timing npm:load:mkdirplogs Completed in 0ms
npm timing npm:load:setTitle Completed in 2ms
npm timing config:load:flatten Completed in 3ms
npm timing npm:load:display Completed in 13ms
npm timing npm:load:logFile Completed in 5ms
npm timing npm:load:timers Completed in 0ms
npm timing npm:load:configScope Completed in 0ms
npm timing npm:load Completed in 36ms
npm timing arborist:ctor Completed in 1ms
npm http fetch GET 200 https://registry.npmjs.org/enet-api 792ms (cache revalidated)
npm timing arborist:ctor Completed in 0ms
Error: Error: Unable to fetch devices at this time!
    at ENetClient.getDevicesWithParameterFilter (C:\Users\user\AppData\Roaming\npm\node_modules\enet-api\dist\ENetClient.js:230:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Command.<anonymous> (C:\Users\user\AppData\Roaming\npm\node_modules\enet-api\dist\main.js:247:29)
npm timing command:exec Completed in 3367ms
npm timing npm Completed in 3510ms
npm info ok
```

**Comment by huglester** [comment]
I have version 2.3.1
maybe it will solve the problem...
But do it at your own risk :)

**Comment by Archef2000** [comment]
Server or node app

**Comment by archef2000** [comment]
I get the locations but cant choose them

**Comment by archef2000** [comment]
I can see the devices but cant controll them cloud you provide a simple example command for turning on a light

**Comment by huglester** [comment]
well I did not try to do it "manually"
I am just now trying to make "homebridge" to work with this module
https://github.com/lawrencebensaid/homebridge-enet

**Comment by archef2000** [comment]
But have you got the cli working one time

**Comment by archef2000** [comment]
I am trying with Home Assistant but there are no working configs so i try to make them myself but first i need to get it working somehow

**Comment by huglester** [comment]
Okay good luck. I personally use homebridge only. And since this author has homebridge integration in place, I try to make it work. 

But there is some problem with "TypeError: enet_api_1.ENet is not a constructor"

Probably some typescript compilation problem or exporting of classes. 
I am noob at TS and stuff like that.

**Comment by huglester** [comment]
in cli, device ls shows me something like that:

<img width="180" alt="image" src="https://user-images.githubusercontent.com/150731/210112800-60f4b45f-a122-4a26-a726-39b3c505b6e3.png">

**Comment by Archef2000** [comment]
with what command

**Comment by archef2000** [comment]
I only get 
![grafik](https://user-images.githubusercontent.com/69057532/210112859-65cfbf5b-c9ce-4038-8b93-51845801d379.png)

**Comment by archef2000** [comment]
even with  --include-state

**Comment by huglester** [comment]
Or when something is ON:

```
node dist/main.js device ls
```

<img width="195" alt="image" src="https://user-images.githubusercontent.com/150731/210112892-8b99d4a9-bb2b-4ca0-95c2-ea2a19c596a5.png">


are your "actuators" enabled etc. I mean do you have it all set up? 
Can you turn on the lights using default enet app?

**Comment by archef2000** [comment]
Yes the default app is working

**Comment by archef2000** [comment]
Also i don't see all devices in the cli

**Comment by huglester** [comment]
You conneting via local ip? And using admin user?

**Comment by archef2000** [comment]
Both times yes

**Comment by archef2000** [comment]
Cloud you may send a example command to turn on a light

**Comment by huglester** [comment]
I did not try yet :D 
But will try to find anything when I am back at pc

**Comment by huglester** [comment]
well I can't find the exact command to turn on switches now.
The picks I showed with ON status, is when I enabled it via Default ENet APP

**Comment by archef2000** [comment]
What was your result?

**Comment by huglester** [comment]
What do you mean?

**Comment by archef2000** [comment]
Did the cli tool work for you

**Comment by huglester** [comment]
I did not try cli except auth/deauth. 

I now constatly try some build of homebridge enet. And have 0 luck :)))

**Comment by archef2000** [comment]
Cloud you try the cli on your end ?

**Comment by huglester** [comment]
did you make it work?

**Comment by archef2000** [comment]
I found a HACS repo for Home Assistant [mnordseth/enet-homeassistant](https://github.com/mnordseth/enet-homeassistant) and that is what i needed

**Comment by huglester** [comment]
And it does connect to homebridge? Or it only work via home-assistant?

**Comment by archef2000** [comment]
Home Assistant only it has way more Integrations and you could make it with the [HomeKit](https://www.home-assistant.io/integrations/homekit/) interation so it shows up there

**Comment by huglester** [comment]
Hey. This integration seems to work right eith “local” server. No google sdk and similar. Thanks!
